server:
  port: 8084
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/heima?characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.sqc.springboot.domain
eureka:
  client:
    service-url: # EurekaServer地址
      defaultZone: http://127.0.0.1:8089/eureka
  instance:
    prefer-ip-address: true # 当调用getHostname获取实例的hostname时，返回ip而不是host名称
    ip-address: 127.0.0.1 # 指定自己的ip信息，不指定的话会自己寻找



