server:
  port: 8083
spring:
  datasource:
    url: jdbc:h2:file:~/.h2/testBook
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
  h2:
    console:
      path: /h2-console
      enabled: true


